export const CUSTOM_EVENT_TYPE = "custom";

export const EMAIL_TEMPLATE_EVENT_PRESETS = [
  {
    key: "announcement_created",
    label: "Announcement Published",
    category: "Community",
    description: "Prepared for a future community-announcement integration.",
    variables: ["homeowner_name", "association_name", "title", "body", "date"],
  },
  {
    key: "event_created",
    label: "Event Invitation",
    category: "Community",
    description: "Prepared for a future community-event integration.",
    variables: [
      "homeowner_name",
      "association_name",
      "title",
      "description",
      "starts_at",
      "location",
    ],
  },
  {
    key: "welcome_homeowner",
    label: "Welcome New Resident",
    category: "Onboarding",
    description: "Prepared for a future resident-onboarding integration.",
    variables: ["homeowner_name", "association_name", "email", "unit_number", "registration_code"],
  },
  {
    key: "password_reset_otp",
    label: "Forgot Password OTP",
    category: "Security",
    description: "Prepared for the forgot-password OTP flow.",
    variables: [
      "homeowner_name",
      "otp",
      "password_reset_expiry_seconds",
    ],
  },
  {
    key: "service_request_updated",
    label: "Service Request Status",
    category: "Maintenance",
    description: "Prepared for a future service-request integration.",
    variables: [
      "homeowner_name",
      "association_name",
      "ticket_id",
      "title",
      "status",
    ],
  },
  {
    key: "meeting_scheduled",
    label: "Board Meeting Scheduled",
    category: "Governance",
    description: "Prepared for a future meeting integration.",
    variables: ["homeowner_name", "association_name", "title", "date", "location"],
  },
  {
    key: "dues_reminder",
    label: "Assessment Dues Reminder",
    category: "Billing",
    description: "Prepared for a future assessment reminder integration.",
    variables: [
      "homeowner_name",
      "association_name",
      "amount",
      "due_date",
      "unit_number",
    ],
  },
  {
    key: "violation_notice",
    label: "Violation Notice",
    category: "Compliance",
    description: "Prepared for a future compliance integration.",
    variables: [
      "homeowner_name",
      "association_name",
      "violation_type",
      "fine_amount",
      "deadline_date",
      "description",
    ],
  },
  {
    key: "visitor_approved",
    label: "Pre-Approved Visitor Entry",
    category: "Security",
    description: "Prepared for a future visitor-management integration.",
    variables: [
      "homeowner_name",
      "visitor_name",
      "vehicle_number",
      "entry_time",
      "association_name",
    ],
  },
] as const;

export const DEFAULT_EMAIL_TEMPLATE_CONTEXT: Record<string, string> = {
  homeowner_name: "Sarah Jenkins",
  association_name: "Oakridge Estates HOA",
  title: "Annual Community Pool Opening & BBQ",
  body: "We are excited to announce our summer season opening this weekend.",
  date: "October 15, 2026",
  starts_at: "Saturday, 11:00 AM",
  location: "Main Clubhouse & Pool Deck",
  ticket_id: "SR-8492",
  status: "In Progress",
  amount: "$250.00",
  due_date: "November 1, 2026",
  unit_number: "Unit 402 - Bldg B",
  violation_type: "Unauthorized Exterior Alteration",
  fine_amount: "$50.00",
  deadline_date: "October 30, 2026",
  visitor_name: "David Miller",
  vehicle_number: "CA 7XYZ89",
  entry_time: "Today at 2:30 PM",
  description: "Please join us for food, music, and community updates.",
  registration_code: "N8K4P2QZ",
  otp: "482913",
  password_reset_expiry_seconds: "60",
};

export const DEFAULT_EMAIL_TEMPLATE_VALUES = {
  name: "",
  event_type: "",
  custom_event_type: "",
  content_source: "html_file" as const,
  subject: "",
  body: "",
  html_content: "",
  is_active: true,
};
